### ISSUE TITLE
add irc nick to ticket

### ISSUE THREAD

**Issue by austindkelly** [cnaude/PurpleIRC#102]
from irc I have added a @modreq command for reportrts but wondering if i can add in the users nickname to the ticket ie. %nick% in the bot yaml? or is it possible to add in the nick instead of having it report that the ticket was opened by "CONSOLE"?

http://puu.sh/f2s9D/51797651c3.png

      modreq:
        modes: qho
        private: 'false'
        game_command: ticket modreq %ARGS%
        private_listen: 'false'
        ctcp: 'false'
        channel_listen: 'true'
        perm: ''

**Comment by cnaude** [comment]
You can now set a sender option for each command. It will default to CONSOLE. You can set it to %NICK% to replace the sender with IRC user's nick.
http://h.cnaude.org:8081/job/PurpleIRC/242/
http://h.cnaude.org:8081/job/PurpleIRC-spigot/14/

```yaml
modreq:
    modes: qho
    private: 'false'
    game_command: ticket modreq %ARGS%
    private_listen: 'false'
    ctcp: 'false'
    channel_listen: 'true'
    perm: ''
    sender: %NICK%
```
