### ISSUE TITLE
Improve PMs UX: reply command

### ISSUE THREAD

**Issue by AmauryCarrade** [cnaude/PurpleIRC#113]
Hi.

A simple but useful suggestion here: I frequently use the IRC«»IG private messaging system; is it possible to add a reply command, avoiding to type again the whole commands and pseudonyms?

Something like this:
```perl
# In game side
/irc msg JohnDoe Hi
/irc r Another message to JohnDoe

# IRC side
.msg FooBar Hi
.r Another message to FooBar
```
`.r` and `/irc r` would be aliases for `.msg` and `/irc msg`, with as the target, the latest player (or irc user) the sender has sent (or received) a message to (from).  
 

Thanks for reading! (And thanks again for this plugin too (never said too much).)

**Comment by AmauryCarrade** [comment]
Other thing, an `/ir`alias for the `/irc r` in-game command would be useful, to improve UX even more.

**Comment by cnaude** [comment]
I like this idea.

**Comment by cnaude** [comment]
Latest dev builds now have these new features. You will want to add a new custom command to your bot yml like this:
```yaml
      r:
        modes: '*'
        private: 'true'
        ctcp: 'false'
        game_command: '@r'
        private_listen: 'true'
        channel_listen: 'true'
        perm: ''
        sender: CONSOLE
        game_command_usage: ''
        extra_commands: []
        user_masks: []
        output: '%RESULT%'
```
