### ISSUE TITLE
ESS Broadcast does not show in IRC.

### ISSUE THREAD

**Issue by austindkelly** [cnaude/PurpleIRC#119]
So maybe this is by design, but when doing @broadcast (which sends `broadcast <args>` to the console) does not show back up in IRC. 

Is i possible to have ESS broadcast send back to IRC channels when the broadcast is sent?

**Comment by austindkelly** [comment]
This is my bot config for a broadcast, how can i get this to show the same broadcast in IRC when i do the command?

>       bcdiscord:
>         modes: qho
>         private: 'false'
>         game_command: broadcast &6Join the party on &9&lDISCORD &r&5One-Click Voice Chat &b-=-&6 &3 https://goo.gl/CHgCVE
>         private_listen: 'false'
>         ctcp: 'false'
>         channel_listen: 'true'
>         perm: ''
>         sender: CONSOLE
>         game_command_usage: ''
>         extra_commands: []
>         user_masks: []
>         output: '%RESULT%'

**Comment by cnaude** [comment]
Try this:

```yaml
bcdiscord:
    modes: qho
    private: 'false'
    game_command: broadcast &6Join the party on &9&lDISCORD &r&5One-Click Voice Chat &b-=-&6 &3 https://goo.gl/CHgCVE
    extra_commands:
    - 'irc say BOTNAME #CHANNEL &6Join the party on &9&lDISCORD &r&5One-Click Voice Chat &b-=-&6 &3 https://goo.gl/CHgCVE
    private_listen: 'false'
    ctcp: 'false'
    channel_listen: 'true'
    perm: ''
    sender: CONSOLE
    game_command_usage: ''
    extra_commands: []
    user_masks: []
    output: '%RESULT%'
```
