### ISSUE TITLE
file-tailer exclusion regex

### ISSUE THREAD

**Issue by AeSix** [cnaude/PurpleIRC#142]
This regex should work, and does as tested with a regex verifier
```
\[([01]\d|2[0-3]):?([0-5]\d):?([0-5]\d)\]\s\[(Craft Scheduler Thread - 3\/INFO)\]: .+
```
However, this line is continually passed to IRC
```
[19:24:06] [Craft Scheduler Thread - 3/INFO]: [TokenPlugin] Getting initialtokens for 3d8f7ba3-2b7b-329b-a8da-16b670438e35
```
The line is not an indication of a problem and does not need to be resolved - the line being excluded from IRC is the problem.  It is required for my logs, however I wish it not to be displayed in IRC.

**Comment by cnaude** [comment]
I'm wondering if the backslashes are causing a problem in the yml file. Is your entire regex string in single quotes? Can I see what your config looks like?

**Comment by AeSix** [comment]
```
file-tailer:
  enabled: true
  file: <redacted>/logs/latest.log
  extra_files: []
  recipient: '#votes'
  ctcp: false
  excludes:
  - '/\[([01]\d|2[0-3]):?([0-5]\d):?([0-5]\d)\]\s\[(Craft Scheduler Thread - 3\/INFO)\]: .+'
```

I've tried changing it without the single quotes, without the first /, and all combinations.
The default example also does not seem to work.
