### ISSUE TITLE
"No Ident response"

### ISSUE THREAD

**Issue by jrogers1126** [cnaude/PurpleIRC#89]
```
[22:27:51 INFO]: [PurpleIRC] [Tybox] NOT CONNECTED
[22:27:51 INFO]: [PurpleIRC] Setting IdentPassword ...
[22:27:51 INFO]: [PurpleIRC] Enabling SSL and trusting all certificates ...
[22:27:51 INFO]: [PurpleIRC] Using default character set: UTF-8
[22:27:51 INFO]: [PurpleIRC] Max line length: 440
[22:27:51 INFO]: [PurpleIRC] Connecting to "irc.freenode.net:6697" as "Tybox" [SSL: true] [TrustAllCerts: true]
[22:27:52 INFO]: [PurpleIRC] -sinisalo.freenode.net-*** Looking up your hostname...
[22:27:52 INFO]: [PurpleIRC] -sinisalo.freenode.net-*** Checking Ident
[22:27:52 INFO]: [PurpleIRC] -sinisalo.freenode.net-*** No Ident response
[22:27:52 INFO]: [PurpleIRC] -sinisalo.freenode.net-*** Couldn't look up your hostname
[22:27:52 INFO]: [Tybox] Disconnected from IRC server.
```
Never actually connects.  Similar symptom whether using SSL or not, this started a while ago with freenode.  I'm trying to figure if this is something to do with Freenode's recent SASL requirement?  I've tried installing an identd on my server, until I noticed the config.yml option 'enable-ident-server' which I have enabled after uninstalling identd on my server.  Here is the config snippets:

config.yml
```
conn-check-interval: 1000
enable-ident-server: true
channel-check-interval: 100
...
Debug: false
ignore-chat-cancel: false
```

bot.yml
```
nick: Tybox
login: Tybox
realname: ''
server: irc.freenode.net
port: 6697
ssl: true
trust-all-certs: true
bind: ''
max-line-length: 440
charset: ''
show-motd: false
autoconnect: true
password: nickservpasswordhere
ident-password: nickservpasswordhere
quit-message: '&r[&5PurpleIRC&r] &rGood bye!'
message-delay: 1000
raw-message-on-connect: false
raw-message: auth name pass
relay-private-chat: true
command-notify:
  enabled: true
  mode: msg
  recipients:
  - jrogers
  ignore:
  - /example
part-invalid-channels: false
part-invalid-channels-message: I should not be here! Bye!
channel-auto-join-delay: 20
relay-private-chat: true
command-notify:
  enabled: true
  mode: msg
  recipients:
  - Silver[a]
  - SilverFox
  ignore:
  - /example
part-invalid-channels: false
part-invalid-channels-message: I should not be here! Bye!
channel-auto-join-delay: 20
channels:
  '#tybox':
    worlds:
    - '*'
    autojoin: true
    modes: ''
    password: ''
    topic: http://foo.enjin.com/home/m/4466393/article/2515228
    topic-protect: false
    topic-chanserv: true
    shortify: true
    enable-filtering: false
    filter-list:
    - foobar
    enabled-messages:
    - console-chat
    - game-action
    - game-chat
    - game-death
    - game-kick
    - game-join
    - game-quit
    shortify: true
    enable-filtering: false
    filter-list:
    - foobar
    enabled-messages:
    - console-chat
    - game-action
    - game-chat
    - game-death
    - game-kick
    - game-join
    - game-quit
    - game-mode
    - ess-helpop
    - irc-action
    - irc-chat
    - irc-pchat
    - irc-join
    - irc-kick
    - irc-part
    - irc-topic
    - irc-quit
    - irc-nickchange
    - game-quit
    - game-mode
    - ess-helpop
    - irc-action
    - irc-chat
    - irc-pchat
    - irc-join
    - irc-kick
    - irc-part
    - irc-topic
    - irc-quit
    - irc-nickchange
    - irc-mode
    - irc-notice
    - dynmap-web-chat
    - mcmmo-admin-chat
    - mcmmo-party-chat
    - mcmmo-chat
    - faction-public-chat
    - faction-ally-chat
    - faction-enemy-chat
    - hero-Global-chat
    - hero-Global-action
    - irc-nickchange
    - irc-mode
    - irc-notice
    - dynmap-web-chat
    - mcmmo-admin-chat
    - mcmmo-party-chat
    - mcmmo-chat
    - faction-public-chat
    - faction-ally-chat
    - faction-enemy-chat
    - hero-Global-chat
    - hero-Global-action
    - hero-chat
    - hero-action
    - clever-chat
    - titan-chat
    - towny-chat
    - rts-notify
    hero-channel: admin
    towny-channel: irc
    log-irc-to-hero-chat: false
    ops:
    - '*!*sarah@example.com'
    - hero-Global-action
    - hero-chat
    - hero-action
    - clever-chat
    - titan-chat
    - towny-chat
    - rts-notify
    hero-channel: admin
    towny-channel: irc
    log-irc-to-hero-chat: false
    ops:
    - '*!*sarah@example.com'
    muted:
    - KuShy
    ignore-irc-chat: false
    custom-tab-ignore-list:
    - tybox
    hide-join-when-vanished: true
    hide-quit-when-vanished: true
    invalid-command:
      private: false
      ctcp: false
    raw-message: ''
    - '*!*sarah@example.com'
    muted:
    - KuShy
    ignore-irc-chat: false
    custom-tab-ignore-list:
    - tybox
    hide-join-when-vanished: true
    hide-quit-when-vanished: true
    invalid-command:
      private: false
      ctcp: false
    raw-message: ''
    raw-message-on-join: false
    commands:
      chat:
        modes: '*'
        private: 'false'
        ctcp: 'false'
        game_command: '@chat'
        private_listen: 'true'
        channel_listen: 'true'
        perm: ''
      ochat:
    raw-message: ''
    raw-message-on-join: false
    commands:
      chat:
        modes: '*'
        private: 'false'
        ctcp: 'false'
        game_command: '@chat'
        private_listen: 'true'
        channel_listen: 'true'
        perm: ''
      ochat:
        modes: '*'
        private: 'false'
        ctcp: 'false'
        game_command: '@ochat'
        private_listen: 'true'
        channel_listen: 'true'
        perm: ''
      h:
        modes: '*'
        private: 'false'
        ctcp: 'false'
      ochat:
        modes: '*'
        private: 'false'
        ctcp: 'false'
        game_command: '@ochat'
        private_listen: 'true'
        channel_listen: 'true'
        perm: ''
      h:
        modes: '*'
        private: 'false'
        ctcp: 'false'
        game_command: '@hchat'
        private_listen: 'true'
        channel_listen: 'true'
        perm: ''
      msg:
        modes: '*'
        private: 'true'
        ctcp: 'false'
        game_command: '@msg'
        private_listen: 'true'
        channel_listen: 'true'
        ctcp: 'false'
        game_command: '@hchat'
        private_listen: 'true'
        channel_listen: 'true'
        perm: ''
      msg:
        modes: '*'
        private: 'true'
        ctcp: 'false'
        game_command: '@msg'
        private_listen: 'true'
        channel_listen: 'true'
        perm: ''
      list:
        modes: '*'
        private: 'false'
        ctcp: 'false'
        game_command: '@list'
        private_listen: 'true'
        channel_listen: 'true'
        perm: ''
      help:
        modes: '*'
        channel_listen: 'true'
        perm: ''
      list:
        modes: '*'
        private: 'false'
        ctcp: 'false'
        game_command: '@list'
        private_listen: 'true'
        channel_listen: 'true'
        perm: ''
      help:
        modes: '*'
        private: 'false'
        ctcp: 'false'
        game_command: '@help'
        private_listen: 'true'
        channel_listen: 'true'
        perm: ''
      uptime:
        modes: '*'
        private: 'false'
        ctcp: 'false'
        game_command: '@uptime'
        modes: '*'
        private: 'false'
        ctcp: 'false'
        game_command: '@help'
        private_listen: 'true'
        channel_listen: 'true'
        perm: ''
      uptime:
        modes: '*'
        private: 'false'
        ctcp: 'false'
        game_command: '@uptime'
        private_listen: 'true'
        channel_listen: 'true'
        perm: ''
      version:
        modes: '*'
        private: 'false'
        ctcp: 'false'
        game_command: version
        private_listen: 'true'
        channel_listen: 'true'
        perm: ''
        game_command: '@uptime'
        private_listen: 'true'
        channel_listen: 'true'
        perm: ''
      version:
        modes: '*'
        private: 'false'
        ctcp: 'false'
        game_command: version
        private_listen: 'true'
        channel_listen: 'true'
        perm: ''
      lag:
        modes: '*'
        private: 'false'
        ctcp: 'false'
        game_command: lag
        private_listen: 'true'
        channel_listen: 'true'
        perm: ''
      lagmem:
        modes: '*'
        private: 'true'
        perm: ''
      lag:
        modes: '*'
        private: 'false'
        ctcp: 'false'
        game_command: lag
        private_listen: 'true'
        channel_listen: 'true'
        perm: ''
      lagmem:
        modes: '*'
        private: 'true'
        ctcp: 'false'
        game_command: lagmem
        private_listen: 'true'
        channel_listen: 'true'
        perm: ''
      gamemode:
        modes: o
        private: 'false'
        ctcp: 'false'
        game_command: gamemode %ARGS%
        private_listen: 'true'
        channel_listen: 'true'
        perm: ''
```

I can't figure out why it won't connect to the irc server now (just shows the ident error)
